version: 2

sources:
  - name: "{{ var('raw_database') }}"
    description: "Database of ethereum raw"
    database: "{{ var('raw_database') }}"
    schema: "{{ var('raw_schema') }}"
    tables:
      - name: transactions
        description: "ethereum raw transactions"
        identifier: "{{ var('source_table_transactions') }}"
      - name: logs
        description: "ethereum raw logs"
        identifier: "{{ var('source_table_logs') }}"
      - name: traces
        description: "ethereum raw traces"
        identifier: "{{ var('source_table_traces') }}"
      - name: blocks
        description: "ethereum raw blocks"
        identifier: "{{ var('source_table_blocks') }}"
  - name: "{{ var('contracts_database') }}"
    description: "Database of ethereum contract info, including event fragments and method fragments"
    database: "{{ var('contracts_database') }}"
    schema: "{{ var('contracts_schema') }}"
    tables:
      - name: method_fragments
        description: "table of method fragments"
      - name: event_fragments
        description: "table of event fragments"
  - name: "{{ var('decoded_database') }}"
    description: "Database of ethereum decoded"
    database: "{{ var('decoded_database') }}"
    schema: "{{ var('decoded_schema') }}"
    tables:
      - name: decoded_transactions
        description: "ethereum decoded transactions"
        identifier: "{{ var('decoded_table_transactions') }}"
      - name: decoded_logs
        description: "ethereum decoded logs"
        identifier: "{{ var('decoded_table_logs') }}"
      - name: decoded_traces
        description: "ethereum decoded traces"
        identifier: "{{ var('decoded_table_traces') }}"
      - name: decoded_blocks
        description: "ethereum decoded blocks"
        identifier: "{{ var('decoded_table_blocks') }}"