version: 2

sources:
  - name: "{{ var('raw_database') }}"
    description: "Database of ethereum raw"
    database: "{{ var('raw_database') }}"
    schema: "{{ var('raw_schema') }}"
    tables:
      - name: transactions
        description: "ethereum raw transactions"
        identifier: "{{ var('source_table_transactions') }}"
      - name: logs
        description: "ethereum raw logs"
        identifier: "{{ var('source_table_logs') }}"
      - name: traces
        description: "ethereum raw traces"
        identifier: "{{ var('source_table_traces') }}"
      - name: blocks
        description: "ethereum raw blocks"
        identifier: "{{ var('source_table_blocks') }}"
  - name: "{{ var('contracts_database') }}"
    description: "Database of ethereum contract info, including event fragments and method fragments"
    database: "{{ var('contracts_database') }}"
    schema: "{{ var('contracts_schema') }}"
    tables:
      - name: method_fragments
        description: "table of method fragments"
      - name: event_fragments
        description: "table of event fragments"
  - name: "{{ var('decoded_database') }}"
    description: "Database of ethereum decoded"
    database: "{{ var('decoded_database') }}"
    schema: "{{ var('decoded_schema') }}"
    tables:
      - name: decoded_transactions
        description: "ethereum decoded transactions"
        identifier: "{{ var('decoded_table_transactions') }}"
      - name: decoded_logs
        description: "ethereum decoded logs"
        identifier: "{{ var('decoded_table_logs') }}"
      - name: decoded_traces
        description: "ethereum decoded traces"
        identifier: "{{ var('decoded_table_traces') }}"
      - name: decoded_blocks
        description: "ethereum decoded blocks"
        identifier: "{{ var('decoded_table_blocks') }}"
  - name: "{{ var('optimism_raw_database') }}"
    description: "Database of optimism raw"
    database: "{{ var('optimism_raw_database') }}"
    schema: "{{ var('optimism_raw_schema') }}"
    tables:
      - name: transactions
        description: "optimism raw transactions"
        identifier: "{{ var('optimism_source_table_transactions') }}"
      - name: logs
        description: "optimism raw logs"
        identifier: "{{ var('optimism_source_table_logs') }}"
      - name: traces
        description: "optimism raw traces"
        identifier: "{{ var('optimism_source_table_traces') }}"
      - name: blocks
        description: "ethereum raw blocks"
        identifier: "{{ var('optimism_source_table_blocks') }}"
  - name: "{{ var('optimism_decoded_database') }}"
    description: "Database of ethereum decoded"
    database: "{{ var('optimism_decoded_database') }}"
    schema: "{{ var('optimism_decoded_schema') }}"
    tables:
      - name: decoded_optimism_transactions
        description: "optimism decoded transactions"
        identifier: "{{ var('decoded_optimism_transactions') }}"
      - name: decoded_optimism_logs
        description: "optimism decoded logs"
        identifier: "{{ var('decoded_optimism_logs') }}"
      - name: decoded_optimism_traces
        description: "optimism decoded traces"
        identifier: "{{ var('decoded_optimism_traces') }}"
      - name: decoded_optimism_blocks
        description: "optimism decoded blocks"
        identifier: "{{ var('decoded_optimism_blocks') }}"
  - name: "{{ var('testnet_base_raw_database') }}"
    description: "Database of testnet base raw"
    database: "{{ var('testnet_base_raw_database') }}"
    schema: "{{ var('testnet_base_raw_schema') }}"
    tables:
      - name: transactions
        description: "testnet_base raw transactions"
        identifier: "{{ var('testnet_base_source_table_transactions') }}"
      - name: logs
        description: "testnet_base raw logs"
        identifier: "{{ var('testnet_base_source_table_logs') }}"
      - name: traces
        description: "testnet_base raw traces"
        identifier: "{{ var('testnet_base_source_table_traces') }}"
      - name: blocks
        description: "testnet base raw blocks"
        identifier: "{{ var('testnet_base_source_table_blocks') }}"
  - name: "{{ var('testnet_base_decoded_database') }}"
    description: "Database of ethereum decoded"
    database: "{{ var('testnet_base_decoded_database') }}"
    schema: "{{ var('testnet_base_decoded_schema') }}"
    tables:
      - name: decoded_testnet_base_transactions
        description: "testnet_base decoded transactions"
        identifier: "{{ var('decoded_testnet_base_transactions') }}"
      - name: decoded_testnet_base_logs
        description: "testnet_base decoded logs"
        identifier: "{{ var('decoded_testnet_base_logs') }}"
      - name: decoded_testnet_base_traces
        description: "testnet_base decoded traces"
        identifier: "{{ var('decoded_testnet_base_traces') }}"
      - name: decoded_testnet_base_blocks
        description: "testnet_base decoded blocks"
        identifier: "{{ var('decoded_testnet_base_blocks') }}"
  - name: "{{ var('polygon_raw_database') }}"
    description: "Database of polygon raw"
    database: "{{ var('polygon_raw_database') }}"
    schema: "{{ var('polygon_raw_schema') }}"
    tables:
      - name: transactions
        description: "polygon raw transactions"
        identifier: "{{ var('polygon_source_table_transactions') }}"
      - name: logs
        description: "polygon raw logs"
        identifier: "{{ var('polygon_source_table_logs') }}"
      - name: traces
        description: "polygon raw traces"
        identifier: "{{ var('polygon_source_table_traces') }}"
      - name: blocks
        description: "polygon raw blocks"
        identifier: "{{ var('polygon_source_table_blocks') }}"
  - name: "{{ var('polygon_decoded_database') }}"
    description: "Database of polygon decoded"
    database: "{{ var('polygon_decoded_database') }}"
    schema: "{{ var('polygon_decoded_schema') }}"
    tables:
      - name: decoded_polygon_transactions
        description: "polygon decoded transactions"
        identifier: "{{ var('decoded_polygon_transactions') }}"
      - name: decoded_polygon_logs
        description: "polygon decoded logs"
        identifier: "{{ var('decoded_polygon_logs') }}"
      - name: decoded_polygon_traces
        description: "polygon decoded traces"
        identifier: "{{ var('decoded_polygon_traces') }}"
      - name: decoded_polygon_blocks
        description: "polygon decoded blocks"
        identifier: "{{ var('decoded_polygon_blocks') }}"
